services:
  frontend:
    image: onthesafari/account-manager-frontend
    build:
      context: ./Frontend
    env_file:
      - ".env"
    ports:
      - "5173:5173"
    volumes:
    # don't copy the node_modules to prevent the volume hosted on windows from overwriting the linux packages on the container
      - ./Frontend/src:/usr/src/app/src
    depends_on:
      - backend
  backend:
    image: onthesafari/account-manager-backend
    env_file:
      - ".env"
    build:
      context: ./Backend
    ports:
      - "8080:8080"
    volumes:
      - ./Backend:/usr/src/app
    depends_on:
      - database
  database:
    image: "postgres:latest"
    env_file:
      - ".env"
    ports:
      - '5432:5432'
    volumes:
      - ./Database/data:/var/lib/postgresql/data
volumes:
  database:
    driver: local
