"""remove redundant 'name' column from activity

Revision ID: 16e53ded2c15
Revises: 582f6d893e7f
Create Date: 2026-02-02 22:26:43.927097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16e53ded2c15'
down_revision: Union[str, Sequence[str], None] = '582f6d893e7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('activity_name_key'), 'activity', type_='unique')
    op.drop_column('activity', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('activity_name_key'), 'activity', ['name'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
