"""remove unique constraint from resource name

Revision ID: 1f6b5d680c33
Revises: 3954895ae7df
Create Date: 2026-02-26 22:50:52.834053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f6b5d680c33'
down_revision: Union[str, Sequence[str], None] = '3954895ae7df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('resource_name_key'), 'resource', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('resource_name_key'), 'resource', ['name'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
