"""add passhash col to Person

Revision ID: 582f6d893e7f
Revises: 81d9751752ef
Create Date: 2026-01-23 21:34:10.433643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '582f6d893e7f'
down_revision: Union[str, Sequence[str], None] = '81d9751752ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('passhash', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('person', 'passhash')
    # ### end Alembic commands ###
