"""add quantity column to resource

Revision ID: 69f066c28818
Revises: 16e53ded2c15
Create Date: 2026-02-02 22:27:24.140622

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "69f066c28818"
down_revision: Union[str, Sequence[str], None] = "16e53ded2c15"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("resource", sa.Column("quantity", sa.Integer()))
    op.execute("update resource set quantity = 100")
    op.alter_column("resource", "quantity", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("resource", "quantity")
    # ### end Alembic commands ###
