name: Deploy

on:
    push:
        branches: [main]
    workflow_dispatch:

jobs:
    test:
        uses: ./.github/workflows/test-backend.yml

    deploy:
        needs: test
        runs-on: ubuntu-latest

        permissions:
            id-token: write
            contents: read

        steps:
            - uses: actions/checkout@v4

            - id: 'auth'
              name: 'Authenticate to Google Cloud'
              uses: 'google-github-actions/auth@v2'
              with:
                  create_credentials_file: true
                  workload_identity_provider: ${{secrets.WORKLOAD_IDENTITY_PROVIDER}}
                  service_account: ${{secrets.SERVICE_ACCOUNT_EMAIL}}

            - name: Set up gcloud
              uses: google-github-actions/setup-gcloud@v2

            - name: Build Docker Image
              run: |
                  docker compose build backend

            - name: Tag Docker Image
              run: |
                  docker tag onthesafari/account-manager-backend:latest \
                  us-central1-docker.pkg.dev/${{secrets.GCP_PROJECT_ID}}/account-manager-backend/account-manager-backend:latest

            - name: Push Docker Image
              run: |
                  docker push us-central1-docker.pkg.dev/${{secrets.GCP_PROJECT_ID}}/account-manager-backend/account-manager-backend:latest

            - id: 'deploy-cloud-run'
              name: Deploy Cloud Run
              run: |
                  gcloud run deploy my-service \
                    --project ${{secrets.GCP_PROJECT_ID}} \
                    --image us-central1-docker.pkg.dev/${{secrets.GCP_PROJECT_ID}}/account-manager-backend/account-manager-backend:latest \
                    --env-vars-file ./env.yaml \
                    --set-secrets ${{secrets.SECRETS_STRING}} \
                    --region us-central1 \
                    --allow-unauthenticated

            - name: Install Firebase CLI
              run: npm install -g firebase-tools

            # no token needed because alerady authenticated to GCloud service account
            - name: Deploy Firebase
              run: |
                  cd frontend
                  npm install
                  npm run build
                  firebase deploy --project ${{secrets.GCP_PROJECT_ID}}
